Repository KB-IT-s-Your-Life-Final-Project/Back-End, pull requests merged in 2025-07, with the labels that each got.

#12 [Fix] RootConfig 수정 #10
  src/main/java/cheongsan/common/config/RootConfig.java
Labels: 🐞fix

#17 [Feature] 수입/지출/상환일 데이터 조회 API #3
  build.gradle
  src/main/java/cheongsan/common/config/ServletConfig.java
  src/main/java/cheongsan/domain/debt/controller/RepaymentCalendarController.java
  src/main/java/cheongsan/domain/debt/dto/DailyRepaymentDTO.java
  src/main/java/cheongsan/domain/debt/dto/RepaymentCalendarDTO.java
  src/main/java/cheongsan/domain/debt/mapper/DebtMapper.java
  src/main/java/cheongsan/domain/debt/service/DebtService.java
  src/main/java/cheongsan/domain/debt/service/DebtServiceImpl.java
  src/main/java/cheongsan/domain/deposit/controller/DepositController.java
  src/main/java/cheongsan/domain/deposit/dto/DailyTransactionDTO.java
  src/main/java/cheongsan/domain/deposit/dto/MonthlyTransactionDTO.java
  src/main/java/cheongsan/domain/deposit/entity/Transaction.java
  src/main/java/cheongsan/domain/deposit/mapper/DepositMapper.java
  src/main/java/cheongsan/domain/deposit/service/DepositService.java
  src/main/java/cheongsan/domain/deposit/service/DepositServiceImpl.java
  src/main/resources/mapper/DebtMapper.xml
  src/main/resources/mapper/DepositMapper.xml
Labels: ✨ feature

#29 [Feature] 대출 상환율 조회 API #27
  src/main/java/cheongsan/domain/debt/controller/DebtController.java
  src/main/java/cheongsan/domain/debt/dto/RepaymentRatioResponseDTO.java
  src/main/java/cheongsan/domain/debt/entity/DebtRepaymentRatio.java
  src/main/java/cheongsan/domain/debt/mapper/DebtMapper.java
  src/main/java/cheongsan/domain/debt/service/DebtService.java
  src/main/java/cheongsan/domain/debt/service/DebtServiceImpl.java
  src/main/resources/mapper/DebtMapper.xml
Labels: ✨ feature

#56 [Refactor] DebtMapper의 getLoanDetail수정 #53
  src/main/java/cheongsan/domain/debt/dto/DebtDetailResponseDTO.java
  src/main/java/cheongsan/domain/debt/mapper/DebtMapper.java
  src/main/java/cheongsan/domain/debt/service/DebtServiceImpl.java
  src/main/resources/mapper/DebtMapper.xml
Labels: ♻️ refactor

#60 [Feature] 관리자 페이지 - 전체 회원 조회 및 회원 삭제 #57
  src/main/java/cheongsan/domain/admin/controller/AdminController.java
  src/main/java/cheongsan/domain/admin/dto/AdminUserListDTO.java
  src/main/java/cheongsan/domain/admin/entity/AdminUser.java
  src/main/java/cheongsan/domain/admin/mapper/AdminMapper.java
  src/main/java/cheongsan/domain/admin/service/AdminService.java
  src/main/java/cheongsan/domain/admin/service/AdminServiceImpl.java
  src/main/resources/mapper/AdminMapper.xml
Labels: ✨ feature
